### ISSUE TITLE
Help popular auto value extensions adopt incremental processing

### ISSUE THREAD

**Issue by bingranl** [google/auto#673]
- [x] auto-value-parcel: [Merged](https://github.com/rharter/auto-value-parcel/issues/131)
- [x] auto-value-gson: [Merged](https://github.com/rharter/auto-value-gson/issues/179)
- [x] auto-value-cursor: [Supported since 2.0.0-rc1](https://github.com/gabrielittner/auto-value-cursor/releases/tag/2.0.0-rc1)
- [x] paperparcel: [Open issue](https://github.com/grandstaish/paperparcel/issues/218)
- [x] auto-value-moshi: [Merged](https://github.com/rharter/auto-value-moshi/issues/112)
- [x] auto-value-redacted: [Supported since 1.1.0](https://github.com/square/auto-value-redacted/releases/tag/1.1.0)
- [x] auto-value-with: [Supported since 1.1.0-rc1](https://github.com/gabrielittner/auto-value-with/releases/tag/1.1.0-rc1)

**Comment by autonomousapps** [comment]
Here's an associated issue on gradle/gradle: https://github.com/gradle/gradle/issues/5277

**Comment by tbroyer** [comment]
Fwiw, autovalue extensions are not processors themselves. There's a new API in 1.6.3rc1 to be implemented by extensions: http://static.javadoc.io/com.google.auto.value/auto-value-annotations/1.6.3rc1/com/google/auto/value/extension/AutoValueExtension.html#incrementalType-javax.annotation.processing.ProcessingEnvironment-

**Comment by bingranl** [comment]
Yeah, our goal is to let extensions figure out if they are compatible with incremental processing and implement that new API.

**Comment by gabrielittner** [comment]
I'll look into my two extensions later this (with and cursor).

**Comment by tbroyer** [comment]
I meant: the open issues linked above (auto-value-gson and auto-value-gson) don't talk about the AutoValueExtension API, they only link to Gradle's documentation.

**Comment by gabrielittner** [comment]
auto-value-with 1.1.0-rc1 and auto-value-cursor 2.0.0-rc1 are on their way to maven central. Both are `ISOLATING`.

**Comment by bingranl** [comment]
@gabrielittner Great, thanks!!

**Comment by hzsweers** [comment]
auto-value-gson and auto-value-moshi both support this now (extensions are `ISOLATING` and the factory processors are `AGGREGATING`), and will be in their next releases

**Comment by bingranl** [comment]
auto-value-redacted is `ISOLATING` now. auto-value-bundle is removed from the list since it is not released.

**Comment by emartynov** [comment]
People, what about AutoFactory?

**Comment by bejibx** [comment]
PaperParcel supports incap since 2.0.7, see [changelog](https://github.com/grandstaish/paperparcel/blob/master/CHANGELOG.md).

**Comment by bingranl** [comment]
@bejibx Thanks for great work! I am closing this issue because all of the popular auto value extensions support incremental annotation processing! Thanks everyone!
